#!/usr/bin/env python3
"""txt2vst HuggingFace Space — Gradio app for text-to-VST generation.

Wraps prompt2spec.py + forge as a zero-shot rule-based pipeline.
Upload to HuggingFace Spaces as a Gradio app.
"""

import json, sys, os, tempfile, zipfile, shutil
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent))

import gradio as gr
from prompt2spec import parse_prompt


def generate_spec(prompt: str) -> tuple[str, str | None]:
    """Parse prompt and return spec JSON + downloadable ZIP."""
    if not prompt or len(prompt.strip()) < 3:
        return "Please enter a description of your VST plugin.", None

    try:
        spec = parse_prompt(prompt)
    except Exception as e:
        return f"Error parsing prompt: {e}", None

    spec_json = json.dumps(spec, indent=2)
    name = spec["plugin"]["name"]
    fn = name.lower()

    # Build ZIP
    tmp = tempfile.mkdtemp()
    zip_path = os.path.join(tmp, f"{fn}-vst-project.zip")

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{fn}/spec.json", spec_json)

        zf.writestr(f"{fn}/build.sh", f"""#!/usr/bin/env bash
set -euo pipefail
echo "=== txt2vst Project Builder ==="

command -v python3 >/dev/null 2>&1 || {{ echo "python3 required"; exit 1; }}
command -v cmake >/dev/null 2>&1 || {{ echo "cmake required (brew install cmake)"; exit 1; }}
command -v git >/dev/null 2>&1 || {{ echo "git required"; exit 1; }}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

if [ ! -d "txt2vst" ]; then
  echo "[1/4] Cloning txt2vst engine..."
  git clone https://github.com/fabriziosalmi/txt2vst.git txt2vst
else
  echo "[1/4] txt2vst engine found, updating..."
  cd txt2vst && git pull && cd ..
fi

echo "[2/4] Generating {name} source..."
python3 txt2vst/forge.py spec.json ./project

echo "[3/4] Building VST3..."
cd project
cmake -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release

echo "[4/4] Installing..."
VST3_DIR="$HOME/Library/Audio/Plug-Ins/VST3"
if [ "$(uname)" = "Linux" ]; then
  VST3_DIR="$HOME/.vst3"
fi
mkdir -p "$VST3_DIR"
find build -name "*.vst3" -exec cp -r {{}} "$VST3_DIR/" \\;

echo ""
echo "=== Done! ==="
echo "VST3 installed to: $VST3_DIR"
echo "Restart your DAW to load {name}"
""")

        zf.writestr(f"{fn}/README.md", f"""# {name}

Generated by [txt2vst](https://txt2vst.com) — 10M+ unique sound combinations.

## Quick Start

### For Producers (Ableton / FL / Logic)
```bash
chmod +x build.sh && ./build.sh
```
Restart your DAW. {name} appears under VST3 instruments.

### For Sound Engineers
```bash
# Edit spec.json to fine-tune voice params, FX chain, mastering preset
./build.sh
```

### For Developers
```bash
python3 txt2vst/forge.py spec.json ./project
cd project && cmake -B build && cmake --build build
```

## Requirements
- macOS 12+ / Linux / Windows 10+
- Python 3.10+, CMake 3.22+, C++17 compiler
- JUCE 7 (auto-fetched by CMake)

## Spec
```json
{spec_json}
```

---
*Generated by txt2vst.com*
""")

    return spec_json, zip_path


# ── Examples ──────────────────────────────────────────────────────────────────
EXAMPLES = [
    "drum machine with kick snare hats, acid bass, delay and reverb, neon theme, punchy mastering",
    "ambient pad synth with strings and FM bells, wide stereo mastering, frost colors",
    "4 channel techno groovebox with kick hats clap and acid bass, distortion, industrial look",
    "simple bass synth with sub bass and compressor",
    "lo-fi organ and pluck with chorus and phaser, vapor theme",
    "aggressive drum machine: kick snare tom perc clap hats, brass stabs, radio mastering, blood theme",
    "minimal synth with lead and noise, transparent mastering, obsidian UI",
    "groovebox called NeonPulse with kick snare hats bass and pad, delay reverb eq, matrix theme",
]

# ── Gradio UI ─────────────────────────────────────────────────────────────────

DESCRIPTION = """# txt2vst

**Text to VST3 Plugin in One Command**

Describe your dream instrument in natural language. Get a complete VST3 project ready to build.

**Engine:** 16 voice archetypes / 8 FX processors / 24 UI themes / 7 mastering presets / 240M+ combinations

**How it works:**
1. Describe your plugin below
2. Download the project ZIP
3. Run `chmod +x build.sh && ./build.sh`
4. Restart your DAW — your plugin is ready
"""

with gr.Blocks(
    title="txt2vst — Text to VST in One Command",
    theme=gr.themes.Base(
        primary_hue="emerald",
        secondary_hue="blue",
        neutral_hue="slate",
        font=gr.themes.GoogleFont("Inter"),
        font_mono=gr.themes.GoogleFont("JetBrains Mono"),
    ),
    css="""
    .gradio-container { max-width: 900px !important; }
    #spec-output textarea { font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; }
    """
) as demo:
    gr.Markdown(DESCRIPTION)

    with gr.Row():
        prompt_input = gr.Textbox(
            label="Describe your VST plugin",
            placeholder="e.g., drum machine with kick snare hats, acid bass, delay and reverb, punchy mastering",
            lines=3,
            scale=4,
        )
        generate_btn = gr.Button("Generate", variant="primary", scale=1, min_width=120)

    with gr.Row():
        spec_output = gr.Code(
            label="Generated spec.json",
            language="json",
            lines=20,
            elem_id="spec-output",
        )

    zip_output = gr.File(label="Download Project ZIP")

    gr.Examples(
        examples=[[e] for e in EXAMPLES],
        inputs=[prompt_input],
    )

    generate_btn.click(
        fn=generate_spec,
        inputs=[prompt_input],
        outputs=[spec_output, zip_output],
    )
    prompt_input.submit(
        fn=generate_spec,
        inputs=[prompt_input],
        outputs=[spec_output, zip_output],
    )

    gr.Markdown("""
---
**Links:** [GitHub](https://github.com/fabriziosalmi/txt2vst) | [Website](https://txt2vst.com) | [Dataset](https://huggingface.co/datasets/fabriziosalmi/txt2vst)

*16 voices + 8 FX + 24 themes + 7 mastering = 240M+ unique combinations. Zero ML, pure structured generation.*
""")

if __name__ == "__main__":
    demo.launch()
