#!/usr/bin/env python3
"""txt2vst HuggingFace Space — Gradio app for text-to-VST generation.

Wraps prompt2spec.py + forge as a zero-shot rule-based pipeline.
Upload to HuggingFace Spaces as a Gradio app.
"""

import json, sys, os, tempfile, zipfile, shutil
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parent))

import gradio as gr
from prompt2spec import parse_prompt


def generate_spec(prompt: str) -> tuple[str, str | None]:
    """Parse prompt and return spec JSON + downloadable ZIP."""
    if not prompt or len(prompt.strip()) < 3:
        return "Please enter a description of your VST plugin.", None

    try:
        spec = parse_prompt(prompt)
    except Exception as e:
        return f"Error parsing prompt: {e}", None

    spec_json = json.dumps(spec, indent=2)
    name = spec["plugin"]["name"]
    fn = name.lower()

    # Build ZIP
    tmp = tempfile.mkdtemp()
    zip_path = os.path.join(tmp, f"{fn}-vst-project.zip")

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{fn}/spec.json", spec_json)

        zf.writestr(f"{fn}/build.sh", f"""#!/usr/bin/env bash
set -euo pipefail
echo "=== txt2vst Project Builder ==="

command -v python3 >/dev/null 2>&1 || {{ echo "python3 required"; exit 1; }}
command -v cmake >/dev/null 2>&1 || {{ echo "cmake required (brew install cmake)"; exit 1; }}
command -v git >/dev/null 2>&1 || {{ echo "git required"; exit 1; }}

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

if [ ! -d "txt2vst" ]; then
  echo "[1/4] Cloning txt2vst engine..."
  git clone https://github.com/fabriziosalmi/txt2vst.git txt2vst
else
  echo "[1/4] txt2vst engine found, updating..."
  cd txt2vst && git pull && cd ..
fi

echo "[2/4] Generating {name} source..."
python3 txt2vst/forge.py spec.json ./project

echo "[3/4] Building VST3..."
cd project
cmake -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release

echo "[4/4] Installing..."
VST3_DIR="$HOME/Library/Audio/Plug-Ins/VST3"
if [ "$(uname)" = "Linux" ]; then
  VST3_DIR="$HOME/.vst3"
fi
mkdir -p "$VST3_DIR"
find build -name "*.vst3" -exec cp -r {{}} "$VST3_DIR/" \\;

echo ""
echo "=== Done! ==="
echo "VST3 installed to: $VST3_DIR"
echo "Restart your DAW to load {name}"
""")

        zf.writestr(f"{fn}/README.md", f"""# {name}

Generated by [txt2vst](https://txt2vst.com) — 10M+ unique sound combinations.

## Quick Start

### For Producers (Ableton / FL / Logic)
```bash
chmod +x build.sh && ./build.sh
```
Restart your DAW. {name} appears under VST3 instruments.

### For Sound Engineers
```bash
# Edit spec.json to fine-tune voice params, FX chain, mastering preset
./build.sh
```

### For Developers
```bash
python3 txt2vst/forge.py spec.json ./project
cd project && cmake -B build && cmake --build build
```

## Requirements
- macOS 12+ / Linux / Windows 10+
- Python 3.10+, CMake 3.22+, C++17 compiler
- JUCE 7 (auto-fetched by CMake)

## Spec
```json
{spec_json}
```

---
*Generated by txt2vst.com*
""")

    return spec_json, zip_path


# ── Examples ──────────────────────────────────────────────────────────────────
EXAMPLES = [
    "drum machine with kick snare hats, acid bass, delay and reverb, neon theme, punchy mastering",
    "ambient pad synth with strings and FM bells, wide stereo mastering, frost colors",
    "4 channel techno groovebox with kick hats clap and acid bass, distortion, industrial look",
    "simple bass synth with sub bass and compressor",
    "lo-fi organ and pluck with chorus and phaser, vapor theme",
    "aggressive drum machine: kick snare tom perc clap hats, brass stabs, radio mastering, blood theme",
    "minimal synth with lead and noise, transparent mastering, obsidian UI",
    "groovebox called NeonPulse with kick snare hats bass and pad, delay reverb eq, matrix theme",
]

# ── Gradio UI — HuggingFace native style ──────────────────────────────────────

DESCRIPTION = """<div style="text-align:center;margin-bottom:1rem;">
<h1 style="font-size:2rem;font-weight:700;margin:0;">🎹 txt2vst</h1>
<p style="color:#6b7280;margin:0.3rem 0 0;font-size:1.05rem;">Text → VST3 Plugin — describe your instrument, download the project, build in one command.</p>
</div>

<div style="display:flex;gap:0.75rem;justify-content:center;flex-wrap:wrap;margin-bottom:0.5rem;font-size:0.82rem;">
<span style="background:#fef3c7;color:#92400e;padding:0.25rem 0.7rem;border-radius:9999px;font-weight:500;">16 Voices</span>
<span style="background:#dbeafe;color:#1e40af;padding:0.25rem 0.7rem;border-radius:9999px;font-weight:500;">8 FX</span>
<span style="background:#ede9fe;color:#5b21b6;padding:0.25rem 0.7rem;border-radius:9999px;font-weight:500;">24 Themes</span>
<span style="background:#d1fae5;color:#065f46;padding:0.25rem 0.7rem;border-radius:9999px;font-weight:500;">7 Mastering</span>
<span style="background:#fee2e2;color:#991b1b;padding:0.25rem 0.7rem;border-radius:9999px;font-weight:500;">240M+ Combos</span>
</div>
"""

with gr.Blocks(
    title="txt2vst — Text to VST in One Command",
    theme=gr.themes.Default(
        primary_hue="amber",
        secondary_hue="yellow",
        neutral_hue="gray",
        font=gr.themes.GoogleFont("Source Sans Pro"),
        font_mono=gr.themes.GoogleFont("IBM Plex Mono"),
        radius_size=gr.themes.sizes.radius_md,
    ),
    fill_width=True,
    css="""
    .gradio-container { max-width: 860px !important; margin: 0 auto !important; padding: 1.5rem !important; }
    .gr-button-primary { background: linear-gradient(to bottom right, #f59e0b, #f97316) !important;
        border: none !important; color: white !important; font-weight: 600 !important;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1) !important; }
    .gr-button-primary:hover { filter: brightness(1.05) !important; transform: translateY(-1px) !important; }
    #spec-output textarea { font-family: 'IBM Plex Mono', monospace !important; font-size: 0.82rem !important;
        background: #1e1e2e !important; color: #a6e3a1 !important; border-radius: 8px !important; }
    .gr-examples .gr-sample-textbox { font-size: 0.82rem !important; }
    footer { display: none !important; }
    """
) as demo:
    gr.HTML(DESCRIPTION)

    with gr.Group():
        with gr.Row(equal_height=True):
            prompt_input = gr.Textbox(
                label="Describe your VST plugin",
                placeholder="drum machine with kick snare hats, acid bass, delay and reverb, neon theme, punchy mastering",
                lines=2,
                scale=5,
            )
            generate_btn = gr.Button("⚡ Generate", variant="primary", scale=1, min_width=140)

    with gr.Row():
        with gr.Column(scale=3):
            spec_output = gr.Code(
                label="spec.json",
                language="json",
                lines=18,
                elem_id="spec-output",
            )
        with gr.Column(scale=1):
            zip_output = gr.File(label="📦 Project ZIP")
            gr.Markdown("""
<div style="font-size:0.78rem;color:#6b7280;line-height:1.5;margin-top:0.5rem;">
<strong>After download:</strong><br/>
<code style="font-size:0.75rem;">chmod +x build.sh && ./build.sh</code><br/>
Restart DAW → plugin ready.
</div>""")

    with gr.Accordion("💡 Try these examples", open=False):
        gr.Examples(
            examples=[[e] for e in EXAMPLES],
            inputs=[prompt_input],
            label="",
        )

    generate_btn.click(fn=generate_spec, inputs=[prompt_input], outputs=[spec_output, zip_output])
    prompt_input.submit(fn=generate_spec, inputs=[prompt_input], outputs=[spec_output, zip_output])

    gr.HTML("""<div style="text-align:center;margin-top:1rem;padding-top:0.75rem;border-top:1px solid #e5e7eb;font-size:0.78rem;color:#9ca3af;">
<a href="https://github.com/fabriziosalmi/txt2vst" style="color:#6b7280;text-decoration:none;">GitHub</a> ·
<a href="https://txt2vst.com" style="color:#6b7280;text-decoration:none;">Website</a> ·
<a href="https://huggingface.co/datasets/fabriziosalmi/txt2vst" style="color:#6b7280;text-decoration:none;">Dataset</a>
&nbsp;—&nbsp; Zero ML, pure structured generation. 240M+ unique instruments.
</div>""")

if __name__ == "__main__":
    demo.launch()

