"""forge.gen_audio — Audio pipeline generators (sequencer, transport, processor)."""

from .spec import const_name, SKELETON


def gen_sequencer_h(spec: dict) -> str:
    """Copy the Sequencer.h template with NUM_CHANNELS substituted."""
    tmpl = (SKELETON / "src" / "Sequencer.h.tmpl").read_text()
    return tmpl.replace("{{NUM_CHANNELS}}", str(len(spec["channels"])))


def gen_transport_sync_h(spec: dict) -> str:
    prefix = spec["plugin"]["prefix"]
    channels = spec["channels"]
    pitched = [(i, c) for i, c in enumerate(channels) if c["type"] == "pitched"]
    first_pi = pitched[0][0] if pitched else -1
    L = []
    L.append("#pragma once")
    L.append("#include <JuceHeader.h>")
    L.append("#include <array>")
    L.append("#include <cmath>")
    L.append('#include "VoiceBank.h"')
    L.append('#include "../Sequencer.h"')
    L.append("")
    L.append("struct TransportSync")
    L.append("{")
    L.append("    static void process(juce::AudioPlayHead* playHead,")
    L.append("                        Sequencer& seq, VoiceBank& voices,")
    L.append("                        std::array<int, Sequencer::NUM_CHANNELS>& lastSteps,")
    L.append("                        int64_t& prevBar, float swing)")
    L.append("    {")
    L.append("        if (!playHead) return;")
    L.append("        const auto pos = playHead->getPosition();")
    L.append("        if (!pos) return;")
    L.append("        const bool playing = pos->getIsPlaying();")
    L.append("        seq.isPlaying.store(playing, std::memory_order_release);")
    L.append("        if (!playing) {")
    L.append("            for (auto& s : seq.currentSteps) s.store(-1, std::memory_order_release);")
    L.append("            lastSteps.fill(-1); prevBar = -1; return;")
    L.append("        }")
    L.append("        const auto ppqOpt = pos->getPpqPosition();")
    L.append("        if (!ppqOpt) return;")
    L.append("        const double ppq = *ppqOpt < 0.0 ? 0.0 : *ppqOpt;")
    L.append("        const double swingFactor = 0.5 + static_cast<double>(swing) * 0.25;")
    L.append("        constexpr double ppqPerPair = 0.5;")
    L.append("        const auto pairIdx = static_cast<int64_t>(std::floor(ppq / ppqPerPair));")
    L.append("        const double posInPair = ppq - static_cast<double>(pairIdx) * ppqPerPair;")
    L.append("        const int64_t globalStep = (posInPair < swingFactor * ppqPerPair)")
    L.append("                                   ? pairIdx * 2 : pairIdx * 2 + 1;")
    L.append("        const int64_t currentBar = globalStep / 16;")
    L.append("        seq.currentBar.store(currentBar, std::memory_order_release);")
    L.append("        prevBar = currentBar;")
    L.append("        for (int ch = 0; ch < Sequencer::NUM_CHANNELS; ++ch) {")
    L.append("            const int len = seq.getPatternLength(ch);")
    L.append("            const int chStep = static_cast<int>(((globalStep % len) + len) % len);")
    L.append("            seq.currentSteps[ch].store(chStep, std::memory_order_release);")
    L.append("            if (chStep == lastSteps[ch]) continue;")
    L.append("            lastSteps[ch] = chStep;")
    L.append("            if (seq.getStep(ch, chStep)) {")
    L.append("                float vel = seq.getVelocity(ch, chStep) / 127.0f;")
    if pitched:
        L.append(f"                if (ch >= {first_pi}) {{")
        L.append(f"                    voices.triggerPitched(ch - {first_pi}, 48, vel);")
        L.append("                } else {")
        L.append("                    voices.trigger(ch, vel);")
        L.append("                }")
    else:
        L.append("                voices.trigger(ch, vel);")
    L.append("            }")
    if pitched:
        L.append(f"            else if (ch >= {first_pi} && voices.isActive(ch))")
        L.append(f"                voices.noteOffPitched(ch - {first_pi});")
    L.append("        }")
    L.append("    }")
    L.append("};")
    L.append("")
    return "\n".join(L)


def gen_processor_h(spec: dict) -> str:
    prefix = spec["plugin"]["prefix"]
    name = spec["plugin"]["name"]
    L = []
    L.append("#pragma once")
    L.append("#include <JuceHeader.h>")
    L.append('#include "core/BusLayout.h"')
    L.append('#include "core/VoiceBank.h"')
    L.append('#include "core/ParamLayout.h"')
    L.append('#include "Sequencer.h"')
    L.append("")
    L.append(f"class {name}Processor : public juce::AudioProcessor")
    L.append("{")
    L.append("public:")
    L.append(f"    {name}Processor();")
    L.append(f"    ~{name}Processor() override = default;")
    L.append("    void prepareToPlay(double sampleRate, int samplesPerBlock) override;")
    L.append("    void releaseResources() override {}")
    L.append("    bool isBusesLayoutSupported(const BusesLayout&) const override;")
    L.append("    void processBlock(juce::AudioBuffer<float>&, juce::MidiBuffer&) override;")
    L.append("    juce::AudioProcessorEditor* createEditor() override;")
    L.append("    bool hasEditor() const override { return true; }")
    L.append('    const juce::String getName() const override { return JucePlugin_Name; }')
    L.append("    bool acceptsMidi() const override { return true; }")
    L.append("    bool producesMidi() const override { return false; }")
    L.append("    bool isMidiEffect() const override { return false; }")
    L.append("    double getTailLengthSeconds() const override { return 2.0; }")
    L.append("    int getNumPrograms() override { return 1; }")
    L.append("    int getCurrentProgram() override { return 0; }")
    L.append("    void setCurrentProgram(int) override {}")
    L.append('    const juce::String getProgramName(int) override { return {}; }')
    L.append("    void changeProgramName(int, const juce::String&) override {}")
    L.append("    void getStateInformation(juce::MemoryBlock&) override;")
    L.append("    void setStateInformation(const void*, int) override;")
    L.append("")
    L.append("    juce::AudioProcessorValueTreeState apvts;")
    L.append("    Sequencer sequencer;")
    L.append("    VoiceBank voiceBank;")
    L.append("    std::atomic<float> currentBpm { 120.0f };")
    L.append("private:")
    L.append(f"    std::array<int, Sequencer::NUM_CHANNELS> lastSteps;")
    L.append("    int64_t prevBar = -1;")
    L.append("    double currentSampleRate = 44100.0;")
    L.append(f"    struct CrossoverState {{ float lpL = 0.0f, lpR = 0.0f; }};")
    L.append(f"    std::array<CrossoverState, {prefix}Bus::COUNT> crossover {{}};")
    L.append("    float crossoverAlpha = 0.04f;")
    L.append(f"    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR({name}Processor)")
    L.append("};")
    L.append("")
    return "\n".join(L)




def gen_processor_cpp(spec: dict) -> str:
    prefix = spec["plugin"]["prefix"]
    name = spec["plugin"]["name"]
    channels = spec["channels"]
    patterns = spec.get("default_patterns", [])
    L = []
    L.append(f'#include "PluginProcessor.h"')
    L.append(f'#include "PluginEditor.h"')
    L.append('#include "core/MidiRouter.h"')
    L.append('#include "core/TransportSync.h"')
    L.append('#include "core/ParamIds.h"')
    L.append('#include "voices/DspConstants.h"')
    L.append("")
    if patterns:
        pats = ", ".join(patterns)
        L.append(f"static constexpr uint64_t kDefaultPatterns[{len(channels)}] = {{ {pats} }};")
    L.append("")
    L.append(f"{name}Processor::{name}Processor()")
    L.append(f'    : AudioProcessor(BusesProperties().withOutput("Main", juce::AudioChannelSet::stereo(), true)),')
    L.append(f'      apvts(*this, nullptr, "STATE", ParamLayout::create()),')
    L.append(f"      voiceBank(apvts)")
    L.append("{")
    L.append("    lastSteps.fill(-1);")
    if patterns:
        L.append(f"    for (int ch = 0; ch < Sequencer::NUM_CHANNELS; ++ch)")
        L.append(f"        sequencer.setPattern(ch, kDefaultPatterns[ch]);")
    L.append("}")
    L.append("")
    L.append(f"bool {name}Processor::isBusesLayoutSupported(const BusesLayout& layouts) const")
    L.append("{ return layouts.outputBuses.size() == 1 && layouts.getMainOutputChannelSet() == juce::AudioChannelSet::stereo(); }")
    L.append("")
    L.append(f"void {name}Processor::prepareToPlay(double sampleRate, int)")
    L.append("{")
    L.append("    lastSteps.fill(-1); prevBar = -1;")
    L.append("    currentSampleRate = sampleRate;")
    L.append(f"    crossoverAlpha = 1.0f - static_cast<float>(std::exp(-Dsp::TWO_PI * 300.0 / sampleRate));")
    L.append("    voiceBank.prepare(sampleRate);")
    L.append(f"    for (auto& cs : crossover) {{ cs.lpL = 0.0f; cs.lpR = 0.0f; }}")
    L.append("}")
    L.append("")
    L.append(f"void {name}Processor::processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midi)")
    L.append("{")
    L.append("    juce::ScopedNoDenormals noDenormals;")
    L.append("    voiceBank.consumeUiTriggers();")
    L.append("    MidiRouter::process(midi, voiceBank);")
    if spec["features"].get("swing"):
        L.append("    const float swing = apvts.getRawParameterValue(ParamId::SWING)->load();")
    else:
        L.append("    const float swing = 0.0f;")
    L.append("    TransportSync::process(getPlayHead(), sequencer, voiceBank, lastSteps, prevBar, swing);")
    L.append("    if (auto* ph = getPlayHead())")
    L.append("        if (auto pos = ph->getPosition())")
    L.append("            if (auto bpm = pos->getBpm())")
    L.append("                currentBpm.store(static_cast<float>(*bpm), std::memory_order_relaxed);")
    L.append("    const int numSamples = buffer.getNumSamples();")
    L.append("    auto* mainL = buffer.getWritePointer(0);")
    L.append("    auto* mainR = buffer.getWritePointer(1);")
    L.append("    buffer.clear();")
    L.append("    constexpr int STACK_MAX = 2048;")
    L.append("    float tmpL[STACK_MAX], tmpR[STACK_MAX];")
    L.append("    for (int offset = 0; offset < numSamples; offset += STACK_MAX) {")
    L.append("    const int blockSize = std::min(numSamples - offset, STACK_MAX);")
    L.append(f"    for (int voice = 0; voice < {prefix}Bus::COUNT; ++voice) {{")
    L.append("        if (!voiceBank.isActive(voice) || !sequencer.isChannelAudible(voice)) continue;")
    L.append("        const float vol = apvts.getRawParameterValue(ParamId::vol(voice))->load();")
    L.append("        std::memset(tmpL, 0, static_cast<size_t>(blockSize) * sizeof(float));")
    L.append("        std::memset(tmpR, 0, static_cast<size_t>(blockSize) * sizeof(float));")
    L.append("        voiceBank.renderBus(voice, tmpL, tmpR, blockSize, vol);")
    L.append("        const float p = apvts.getRawParameterValue(ParamId::pan(voice))->load();")
    L.append("        const float panR = fastSin(p * Dsp::HALF_PI_F);")
    L.append("        const float panL = fastSin((1.0f - p) * Dsp::HALF_PI_F);")
    L.append("        for (int i = 0; i < blockSize; ++i) {")
    L.append("            const float s = tmpL[i];")
    L.append("            mainL[offset + i] += s * panL;")
    L.append("            mainR[offset + i] += s * panR;")
    L.append("        }")
    L.append("    }")
    L.append("    for (int i = 0; i < blockSize; ++i) {")
    L.append("        mainL[offset + i] = fastTanh(mainL[offset + i]);")
    L.append("        mainR[offset + i] = fastTanh(mainR[offset + i]);")
    L.append("    }")
    L.append("    } // offset loop")
    L.append("}")
    L.append("")
    L.append(f"juce::AudioProcessorEditor* {name}Processor::createEditor()")
    L.append(f"{{ return new {name}Editor(*this); }}")
    L.append("")
    L.append(f"void {name}Processor::getStateInformation(juce::MemoryBlock& destData)")
    L.append("{ auto state = apvts.copyState(); copyXmlToBinary(*state.createXml(), destData); }")
    L.append("")
    L.append(f"void {name}Processor::setStateInformation(const void* data, int sizeInBytes)")
    L.append("{")
    L.append("    auto xml = getXmlFromBinary(data, sizeInBytes);")
    L.append("    if (!xml || !xml->hasTagName(apvts.state.getType())) return;")
    L.append("    apvts.replaceState(juce::ValueTree::fromXml(*xml));")
    L.append("}")
    L.append("")
    L.append("juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()")
    L.append(f"{{ return new {name}Processor(); }}")
    L.append("")
    return "\n".join(L)


